service: aws-alcohol-serverless-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  timeout: 16 # 람다 리퀘스트 시간
  stage: dev # 프로덕션 == 실서버 (db도 나누어져있다) # dev == 개발서버

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
